# Generated by Django 5.2.2 on 2025-06-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, unique=True, verbose_name='ICCID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('blocked', 'Заблокирована')], default='inactive', max_length=10, verbose_name='Статус')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Дата активации')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Владелец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sim_management.operator', verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
            },
        ),
    ]
