# Generated by Django 5.2.2 on 2025-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код MCC')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'MCC код',
                'verbose_name_plural': 'MCC коды',
            },
        ),
        migrations.CreateModel(
            name='MNCOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код MNC')),
                ('operator', models.CharField(max_length=50, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'MNC оператор',
                'verbose_name_plural': 'MNC операторы',
            },
        ),
        migrations.CreateModel(
            name='MOBIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Код MOBIL')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'MOBIL код',
                'verbose_name_plural': 'MOBIL коды',
            },
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, unique=True, verbose_name='ICCID')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('operator', models.CharField(blank=True, default='Неизвестный оператор', max_length=50, verbose_name='Оператор')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('blocked', 'Заблокирована')], default='inactive', max_length=10, verbose_name='Статус')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Дата активации')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Владелец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
            },
        ),
    ]
